# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
      - targets:
          - "IP_MONITOR:9093"
rule_files:
  - "alert.rules"
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]
  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']   
  # - job_name: "windows-exporter"
  #   scheme: http
  #   static_configs:
  #     - targets:
  #         - 192.168.18.181:9182
  #       labels:
  #         instance: '192.168.18.181' 
  #     - targets:
  #         - 192.168.18.207:9182
  #       labels:
  #         instance: '192.168.18.207' 

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 192.168.18.128:9100
        labels:
          instance: '192.168.18.128'
      - targets:
          - 192.168.18.241:9100
        labels:
          instance: '192.168.18.241' 
  
  - job_name: 'blackbox'
    scrape_interval: 10s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - 192.168.18.151:8181
        labels: 
          ip: '192.168.18.151-HOSTService'
      - targets: 
        - 192.168.18.151:8282
        labels: 
          ip: '192.168.18.151-OnlineTrading'
      - targets:
        - 192.168.18.241:8182
        labels: 
          ip: '192.168.18.241-jdatafeed'
      - targets:
        - 192.168.18.207:61616
        labels: 
          ip: '192.168.18.207-Activemq'
      - targets:
        - 192.168.18.241:8181
        labels: 
          ip: '192.168.18.241-Bus'
      - targets:
        - 192.168.18.138:8181
        labels: 
          ip: '192.168.18.138-Enginee'

    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: "192.168.18.241:9115"

  - job_name: "haproxy_exporter"
    scheme: http
    static_configs:
    - targets: ["192.168.18.241:9101"]    
    basic_auth:
      username: 'admin'
      password: 'admin'

  - job_name: 'postgres'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 192.168.18.241:9187
       
  - job_name: 'rabbitmq'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 192.168.18.241:9419

  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 192.168.18.241:9121

  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets:
          - 192.168.18.241:8080
        labels: 
          ip: '192.168.18.241'
