{
 "title": "Summary",
 "tags": [ "main" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Haproxy service",
   "type": "stat",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_backend_up", "legendFormat": "{{backend}}-{{instance}}" }
   ]
  },
  {
   "title": "Status service",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}-{{env}}"
    },
    {
     "expr": "(windows_cs_physical_memory_bytes - windows_os_physical_memory_free_bytes) / windows_cs_physical_memory_bytes * 100",
     "legendFormat": "{{instance}}-{{env}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))) * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status Rabbitmq",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 11 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "min(rabbitmq_running)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Status Redis",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "redis_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Status Postgres",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100)/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}} - {{mountpoint}} "
    },
    {
     "expr": "100 - ((windows_logical_disk_free_bytes / windows_logical_disk_size_bytes) * 100)",
     "legendFormat": "{{instance}} - {{volume}}"
    }
   ]
  },
  {
   "title": "Connections Rabbitmq",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consumer Rabbitmq",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_consumers", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Clients Postgres",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clients Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(redis_connected_clients)", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}